feat: use public image
traefik-workshops/traefik-hub-gitops pull request #42
Opened 2024-01-26 15:55 UTC by darkweaver87

Now api-server is publicly available, let's use it :-)

2024-02-05 12:55 UTC, mmatur requested changes

2024-02-05 12:55 UTC, mmatur commented on clusters/kind/flux-system/gotk-sync.yaml
> +    branch: fix/image
```suggestion
    branch: master
```

2024-02-08 12:29 UTC, mmatur commented
Wait for https://github.com/traefik/hub-issues/issues/1107 to me merged

2024-02-08 12:29 UTC, mmatur approved these changes

2024-02-14 10:24 UTC, mloiseleur approved these changes

2024-02-14 10:30 UTC, merged